# This is a basic workflow to help you get started with Actions

name: Wakatime Stats

# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-readme:
    name: Update this repo's README
    runs_on: 
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
